services:
  server:
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - ./model_cache:/app/model_cache
      - /tmp/.cache/huggingface:/tmp/.cache/huggingface
      - /tmp/nltk_data:/tmp/nltk_data